### ISSUE TITLE
--configuration support

### ISSUE THREAD

**Issue by WyriHaximus** [Roave/infection-static-analysis-plugin#27] opened 2020-10-01 18:28 UTC
Can't seem to find it, but does this project support the `--configuration` flag from Infection? I'd like to move some files out of my projects root dir to declutter them. But for some reason I can't find the flag for it in this package.

**Comment by Ocramius** [comment] 2020-10-01 21:51
In theory, all parameters from infection are also reflected here

**Comment by WyriHaximus** [comment] 2020-10-01 22:21
In theory, but not in practice:

![image](https://user-images.githubusercontent.com/147145/94869213-2b430880-0445-11eb-8991-a4e74b97f536.png)

**Comment by Ocramius** [comment] 2020-10-01 22:24
Hmm, seems really weird.

Consider that the two setups are almost exactly the same:

https://github.com/infection/infection/blob/2679bf3efd5d94d000cdda36e191c3cfecdf9e76/bin/infection#L83

vs

https://github.com/Roave/infection-static-analysis-plugin/blob/57e194e643de67b8f38299f13fca88b263f21a4d/bin/roave-infection-static-analysis-plugin#L54-L58

Perhaps it's caused by this bit?

https://github.com/Roave/infection-static-analysis-plugin/blob/57e194e643de67b8f38299f13fca88b263f21a4d/src/Roave/InfectionStaticAnalysis/Bootstrapper.php#L21-L28

I can imagine that infection may be loading the configuration too eagerly there.

Potentially feasible to make it properly lazy via some more reflection nightmares...

**Comment by WyriHaximus** [comment] 2020-10-02 12:31
> Potentially feasible to make it properly lazy via some more reflection nightmares...

To add to that nightmare, the next step would be to make it possible to also pass the psalm config location

**Comment by Ocramius** [comment] 2020-10-02 14:05
Can you make a separate issue for that? :D

**Comment by WyriHaximus** [comment] 2020-10-02 14:09
Done

**Comment by azjezz** [comment] 2021-11-25 23:32
I have a fix for this and #28, PR incoming :)

![image](https://user-images.githubusercontent.com/29315886/143507747-b055cfae-e8c6-45ee-a68a-f0574e53db1b.png)

**Closed as completed** 2021-11-28 20:31 UTC
Labels: enhancement, question
